import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import NextTopLoader from "nextjs-toploader";

const Lexend = localFont({
  src: "./fonts/Lexend-Regular.ttf",
  variable: "--font-lexend",
});

const Cunia = localFont({
  src: "./fonts/Cunia.ttf",
  variable: "--font-cunia",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${Lexend.className} ${Cunia.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background">
        <NextTopLoader color="#a48374" showSpinner={true} />
        <Header />
        <main className="min-h-svh flex-1 flex flex-col items-center justify-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
